from enum import Enum


class Ambiente(str, Enum):
    PRODUCAO = "producao"
    HOMOLOGACAO = "homologacao"


class RegimeTributario(str, Enum):
    NORMAL = "normal"
    SIMPLES_NACIONAL = "simples_nacional"
    MEI = "mei"


class RegimeEspecialTributacao(str, Enum):
    NENHUM = "nenhum"
    ATO_COOPERADO = "ato_cooperado"
    ESTIMATIVA = "estimativa"
    MICROEMPRESA_MUNICIPAL = "microempresa_municipal"
    NOTARIO_REGISTRADOR = "notario_registrador"
    PROFISSIONAL_AUTONOMO = "profissional_autonomo"
    SOCIEDADE_PROFISSIONAIS = "sociedade_profissionais"


class ResponsavelRetencaoIss(str, Enum):
    PRESTADOR = "prestador"
    TOMADOR = "tomador"
    INTERMEDIARIO = "intermediario"


class TributacaoIssqn(str, Enum):
    OPERACAO_TRIBUTAVEL = "1"
    EXPORTACAO_SERVICO = "2"
    NAO_INCIDENCIA = "3"
    IMUNIDADE = "4"


class CstPisCofins(str, Enum):
    CST_00 = "00"
    CST_01 = "01"
    CST_02 = "02"
    CST_03 = "03"
    CST_04 = "04"
    CST_05 = "05"
    CST_06 = "06"
    CST_07 = "07"
    CST_08 = "08"
    CST_09 = "09"


class TipoRetencaoPisCofins(str, Enum):
    NAO_RETIDO = "0"
    RETIDO = "1"
    RETIDO_PESSOA_FISICA = "2"
    PIS_COFINS_CSLL = "3"
    OPERACAO_FINANCEIRA = "4"
    SERVICO_FINANCEIRO = "5"
    SERVICO_INTERMEDIACAO = "6"
    SERVICO_INVESTIMENTO = "7"
    CSLL = "8"
    OUTROS = "9"


class MotivoCancelamento(str, Enum):
    ERRO_EMISSAO = "1"
    SERVICO_NAO_PRESTADO = "2"
    OUTROS = "9"


class CodigoEventoNfse(str, Enum):
    CANCELAMENTO = "101101"
    SOLICITACAO_CANC_ANALISE_FISCAL = "101103"
    CANCELAMENTO_POR_SUBSTITUICAO = "105102"
    CANC_DEFERIDO_ANALISE_FISCAL = "105104"
    CANC_INDEFERIDO_ANALISE_FISCAL = "105105"
    CONFIRMACAO_PRESTADOR = "202201"
    REJEICAO_PRESTADOR = "202205"
    CONFIRMACAO_TOMADOR = "203202"
    REJEICAO_TOMADOR = "203206"
    CONFIRMACAO_INTERMEDIARIO = "204203"
    REJEICAO_INTERMEDIARIO = "204207"
    CONFIRMACAO_TACITA = "205204"
    ANULACAO_REJEICAO = "205208"
    CANCELAMENTO_POR_OFICIO = "305101"
    BLOQUEIO_POR_OFICIO = "305102"
    DESBLOQUEIO_POR_OFICIO = "305103"
    INCLUSAO_NFSE_DAN = "467201"
    TRIBUTOS_NFSE_RECOLHIDOS = "907201"


class StatusProcessamentoDfe(str, Enum):
    REJEICAO = "REJEICAO"
    NENHUM_DOCUMENTO_LOCALIZADO = "NENHUM_DOCUMENTO_LOCALIZADO"
    DOCUMENTOS_LOCALIZADOS = "DOCUMENTOS_LOCALIZADOS"


class TipoDocumentoDfe(str, Enum):
    NENHUM = "NENHUM"
    DPS = "DPS"
    PEDIDO_REGISTRO_EVENTO = "PEDIDO_REGISTRO_EVENTO"
    NFSE = "NFSE"
    EVENTO = "EVENTO"
    CNC = "CNC"


class TipoEventoDfe(str, Enum):
    CANCELAMENTO = "CANCELAMENTO"
    SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL = "SOLICITACAO_CANCELAMENTO_ANALISE_FISCAL"
    CANCELAMENTO_POR_SUBSTITUICAO = "CANCELAMENTO_POR_SUBSTITUICAO"
    CANCELAMENTO_DEFERIDO_ANALISE_FISCAL = "CANCELAMENTO_DEFERIDO_ANALISE_FISCAL"
    CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL = "CANCELAMENTO_INDEFERIDO_ANALISE_FISCAL"
    CONFIRMACAO_PRESTADOR = "CONFIRMACAO_PRESTADOR"
    REJEICAO_PRESTADOR = "REJEICAO_PRESTADOR"
    CONFIRMACAO_TOMADOR = "CONFIRMACAO_TOMADOR"
    REJEICAO_TOMADOR = "REJEICAO_TOMADOR"
    CONFIRMACAO_INTERMEDIARIO = "CONFIRMACAO_INTERMEDIARIO"
    REJEICAO_INTERMEDIARIO = "REJEICAO_INTERMEDIARIO"
    CONFIRMACAO_TACITA = "CONFIRMACAO_TACITA"
    ANULACAO_REJEICAO = "ANULACAO_REJEICAO"
    CANCELAMENTO_POR_OFICIO = "CANCELAMENTO_POR_OFICIO"
    BLOQUEIO_POR_OFICIO = "BLOQUEIO_POR_OFICIO"
    DESBLOQUEIO_POR_OFICIO = "DESBLOQUEIO_POR_OFICIO"
    INCLUSAO_NFSE_DAN = "INCLUSAO_NFSE_DAN"
    TRIBUTOS_NFSE_RECOLHIDOS = "TRIBUTOS_NFSE_RECOLHIDOS"
